# Write your query or mutation here
query huts {
  
  huts {
    hutContentMainSite{
      description,
      icon{
        url
      }
    }
    imagesMainSite{
      formats
      alternativeText
    }
  }
}